language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 1yzYPoAPvcj5jQXqkbDrqnMz2Hp4960ozr48ZcVRnxnvpw+gSMTMWToK3BHUKX63LzxZAFv38RTgZgfAemyE+1DSIyPi6wjhU5f8w8fQJIo1Up9wVkASbZt5LJQvlxfohfWvULbW0y6ZBocfNnImFE5vcebnx5KFP1u9S04atyMnyf5/zd+7iRkh7d+/wjXApNUAeGDdnLgHBEYBJyX50ke5zECrIoN1mzW0xIEOvWk2RP2devixh/MzHmq5KQBHSJKPt/kyda+khH+Fk5gsagZZ0tKVbLxDCQE0McmBmJpjuguEZ7IMIkZ0l3MS7MF8bvsFbAorR9M4fRk4o1eGe0EyURUOffNL39sIchu3pk9Yy3SMmKv/AiEZQkoQPVuIOBxwLpNopnLhb6GlXxjaOHxbrCgr1M4yOJ9pRsxIFp52awzwUo9eWKGxgJHc+vU7lC+F2fgNDhYlvjUQkAt7AT5OQvdoPjQQYr+CL7/chb0UWLCOZ1+s3fYK9sAmRuQD8Ex9NbK/wbV7z98nBVRYdTnX07Wm9gDEe90tAo7PfPcrGGIe4vow+DtU89oSPe3ny75ORZg0e/d2oPJZD6CTChUvLEJZGcYRJBezdtjhqf6SDaMPxxYxwnYfsQtOhNCBojRPgbSc9je7DxRFLk9Pt2PVDiucHVVNJ67a6QL89Fk=
  app: choreganize
  on:
    repo: choreorganize/choreganize
    branch: main
  skip_cleanup: 'true'
