language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: choreganizer
  run: rails db:migrate
  on:
    all_branches: true
  api_key:
    secure: JWrOcTuJSWUxRCsQGSb3owVH628axxuzCdMkfY5sESsw0SRiOQhRTuiUPDj1by2Lkui9SnVyT7EeJx62iII89R1klcg8pw7CtjNUd/0+9IlfLdmaQstSI93uSPi+FtpjVe6eoUAqic5WT/quB9TeaTnl8w/K8SdAGUCwFbHC36OeEzjudQhz7Fr9hqAUxgcQgNeToR9qH1ZRXS9KsBmFLa/VZaX453REgeO6bZ1rHfKFbQnWd4P/9nJEBOKFDdDCL1VSLAsT7UvjFJ0KMD8yeQhn0QpQ7VgcPj7JtrqGtRbsyVopRkFKmLB7Vn12CpZkFu+oqrZ7WjyNX3I2TEE3zptLDnu0y+5bIa87K9OfK8l/QOPIM4R9uUys5DpiRwr+/5XCpndMo+BmY+uEgZ0AR40L+SUJ44a1UwRoE4PqMyBMKvU/1n6ahqlK3PKW/p7DAY90NQYWpCaoUyfP8lEP7p3zeBPMQjAixOfdIIKXJXnaol8gN9kuS+ynm5MRqeIHS4gAzyP8vT01fl8DgiWUgm1y8wy1LhtJbIOK3WY+oKjN/Nyv11yzSdABUVoXm4DKmki7oiQZlOJgcncAz4CGBmfMAFScA6CbRTiZ2ThcXvoU2Y/I0RcsNmc+Qi0SaWq/tY8lKz1KZf0ipxzz7aZ/gukIxdampaulWDYz1eoqqEw=
